config/routes.rb
HullBid2013::Application.routes.draw do

  namespace :admin do  end

  resources :achievements, :only => [:show]
  resources :articles, :only => [:index, :show]
  resources :standalone_articles, :only => [:index, :show], path: 'covid-19-support'
  resources :businesses, :only => [:index]
  resources :business_highlights, :only => [:show]
  resources :contacts, :only => [:new, :create]
  resources :emails, :only => [:show]
  resources :events, :only => [:index, :show]
  resources :event_galleries, :only => [:index, :show]
  resources :faqs, :only => [:index]
  resources :newsletter_subscribers, :only => [:create]
  resources :pages, :only => [:show]
  resources :resources, :only => [:index]
  resources :team_members, :only => [:index]

  namespace :admin do
    manticore_resources :dine_week_participants
    manticore_resources :faqs
    manticore_resources :footfall_data_entries
    manticore_resources :project_images
    manticore_resources :resources
    manticore_resources :event_galleries do
      chronicler_resources :event_gallery_images
    end
    chronicler_resources :achievements
    chronicler_resources :articles
    chronicler_resources :banners
    chronicler_resources :businesses
    chronicler_resources :business_highlights
    chronicler_resources :default_gallery_images
    chronicler_resources :emails do
      post 'change_template', :on => :member
      post 'new_item', :on => :member
      post 'destroy_item', :on => :member
      post 'create_campaign', :on => :member
      post 'update_campaign', :on => :member
      post 'send_test', :on => :member
      post 'send_now', :on => :member
    end
    chronicler_resources :events
    chronicler_resources :pages
    chronicler_resources :partners
    chronicler_resources :projects
    chronicler_resources :team_members
  end

  match "/accessibility" => "application#accessibility"
  match "/site_map" => "application#site_map"
  match "/rss" => "application#rss"

  root :to => "application#index"

  mount Manticore::Engine => "/admin"

end

app/views/admin/pages/_form.html.erb
<%= form_for([:admin, @page]) do |f| %>

  <%= f.error_messages %>
  
  <%= field_set_tag 'Basic' do -%>
    <%= f.hidden_field :layout, :value => 'application' %>
    
    <div class="field">
      <%= f.label :style %><br />
      <%= f.select :style, Page.styles.map{ |x| [t(x), x] } %>
    </div>

    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <%= f.label :tagline %><br />
      <%= f.text_field :tagline %>
    </div>
  <% end -%>

  <%= field_set_tag 'Content' do -%>
    <div class="field">
      <%= f.label :content, 'Main content' %><br />
      <%= f.text_area :content, :class => "tinymce" %>
    </div>
  <% end %>

  <%= field_set_tag 'Images' do -%>
    <%= f.image_field :image %>
  <% end %>

  <%= field_set_tag 'Associated Team Member' do -%>
    <div class="field">
      <%= f.label :team_member_id %><br />
      <%= f.select :team_member_id, options_for_select(TeamMember.all.map{|x| [x.name, x.id]}, :selected => f.object.team_member_id), :include_blank => "None" %>
    </div>
    
    <div class="field">
      <%= f.label :team_member_heading %><br />
      <%= f.text_field :team_member_heading %>
    </div>

    <div class="field">
      <%= f.label :team_member_introduction %><br />
      <%= f.text_area :team_member_introduction %>
    </div>
  <% end %>
  
  <%= render "admin/shared/seo", :f => f %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/admin/pages/edit.html.erb
<%- title 'Edit Page' %>

<div class="admin_functions">
  <%= link_to 'Back', admin_pages_path %>
</div>

<%= render 'form' %>

app/views/admin/pages/index.html.erb
<% title 'Pages' %>

<div class="admin_functions">
  <%= link_to 'New Page', new_admin_page_path %>
</div>

<%= render 'admin/shared/search' %>

<%= informant_table @pages, {
      :headings => [ :title, ih_order(:slug, 'Link'), '', '', '' ],
      :body => [
        :title,
        lambda{|x| link_to page_url(:id => x.slug), page_url(:id => x.slug), :target => "_blank" },
        it_edit_images(:image),
        it_edit,
        it_destroy
      ]
    } %>

<%= paginate @pages %>

app/views/admin/pages/new.html.erb
<%- title 'New Page' %>

<div class="admin_functions">
  <%= link_to 'Back', admin_pages_path %>
</div>

<%= render 'form' %>