config/routes.rb
HullBid2013::Application.routes.draw do

  namespace :admin do  end

  resources :achievements, :only => [:show]
  resources :articles, :only => [:index, :show]
  resources :standalone_articles, :only => [:index, :show], path: 'covid-19-support'
  resources :businesses, :only => [:index]
  resources :business_highlights, :only => [:show]
  resources :contacts, :only => [:new, :create]
  resources :emails, :only => [:show]
  resources :events, :only => [:index, :show]
  resources :event_galleries, :only => [:index, :show]
  resources :faqs, :only => [:index]
  resources :newsletter_subscribers, :only => [:create]
  resources :pages, :only => [:show]
  resources :resources, :only => [:index]
  resources :team_members, :only => [:index]

  namespace :admin do
    manticore_resources :dine_week_participants
    manticore_resources :faqs
    manticore_resources :footfall_data_entries
    manticore_resources :project_images
    manticore_resources :resources
    manticore_resources :event_galleries do
      chronicler_resources :event_gallery_images
    end
    chronicler_resources :achievements
    chronicler_resources :articles
    chronicler_resources :banners
    chronicler_resources :businesses
    chronicler_resources :business_highlights
    chronicler_resources :default_gallery_images
    chronicler_resources :emails do
      post 'change_template', :on => :member
      post 'new_item', :on => :member
      post 'destroy_item', :on => :member
      post 'create_campaign', :on => :member
      post 'update_campaign', :on => :member
      post 'send_test', :on => :member
      post 'send_now', :on => :member
    end
    chronicler_resources :events
    chronicler_resources :pages
    chronicler_resources :partners
    chronicler_resources :projects
    chronicler_resources :team_members
  end

  match "/accessibility" => "application#accessibility"
  match "/site_map" => "application#site_map"
  match "/rss" => "application#rss"

  root :to => "application#index"

  mount Manticore::Engine => "/admin"

end

app/models/event.rb
class Event < ActiveRecord::Base
  
  has_one :event_gallery
  acts_as_taggable_on :categories
  
  mount_uploader :image, EventImageUploader
  
  validates :headline, :summary, :main_content, :start_date, {:presence => true}
  validate :end_date_after_start

  scope :year, lambda{|year| {:conditions => ["year(start_date) = ?", year]}}
  scope :month, lambda{|month| {:conditions => ["month(start_date) = ?", month]}}
  
  def self.years
    Event.where(:display => true).collect{|a| a.start_date.year}.uniq.sort
  end
  
  def self.months(year)
    Event.where(:display => true).year(year).collect{|a| a.start_date.month}.uniq.sort
  end
  
  def start_date_in_future
    if !start_date.blank? and start_date < Date.today
      errors.add(:start_date, "can't be in the past")
    end
  end
  
  def end_date_after_start
    if !end_date.blank? and end_date < start_date
      errors.add(:end_date, "can't be before the start date")
    end
  end
    
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Manticore::ApplicationController

    helper :form
    crops_images_for Event, :image, { :show => { :fit => [440, 1000] } }

    def index
      @events = Event.where(
        ["headline LIKE :search OR summary LIKE :search", {:search => "%#{params[:search]}%"}]
      ).order(params[:order] ||= "start_date DESC").page(params[:page]).per(10)
    end
    
    def new
      @event = Event.new
    end
    
    def create
      @event = Event.new(params[:event])
      if @event.save
        redirect_to admin_events_path, :notice => "Event successfully created."
      else
        render :action => 'new'
      end
    end

    def edit
      @event = Event.find(params[:id])
    end
    
    def update
      @event = Event.find(params[:id])
      if @event.update_attributes(params[:event])
        redirect_to admin_events_path, :notice => "Event successfully updated."
      else
        render :action => 'edit'
      end
    end
    
    def destroy
      @event = Event.find(params[:id])
      @event.destroy
      redirect_to admin_events_path, :notice => "Event destroyed."
    end
    
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
		@current_branch = Willow::Branch.find_by_name('Events')
		params[:page] ||= 1
    if params[:category]
      @title = "#{params[:category]} Events"
      search = Event.where(:display => true).tagged_with(params[:category].to_s, :on => "categories")
    elsif params[:year] && params[:month]
      @title = "#{Date::MONTHNAMES[params[:month].to_i]} #{params[:year]} Events"
      search = Event.where(:display => true).year(params[:year]).month(params[:month])
    elsif params[:year]
      @title = "#{params[:year]} Events"
      search = Event.where(:display => true).year(params[:year])
    else
      @title = "Upcoming/Current Events"
      search = Event.where(
        ["display = ? AND ((end_date IS NULL AND start_date >= ?) OR (end_date IS NOT NULL AND end_date >= ?))", true, Date.today, Date.today]
      )
    end
    @events = search.order("start_date ASC").page(params[:page]).per(10)
    @default_gallery = DefaultGalleryImage.where(:display => true).order(:position).first

    @business_highlight = BusinessHighlight.where(:display => true).order("date desc").first
  end

  def show
    @event = Event.find(params[:id])
    @current_branch = Willow::Branch.find_by_name('Events')
    @business_highlight = BusinessHighlight.where(:display => true).order("date desc").first
  end

end

app/views/admin/events/_form.html.erb
<%= form_for([:admin, @event]) do |f| %>

  <%= f.error_messages %>

  <%= field_set_tag 'Basic' do -%>
    <div class="field">
      <%= f.label :headline, 'Name' %><br />
      <%= f.text_field :headline %>
    </div>

    <div class="field">
      <%= f.label :start_date %><br />
      <% start_date = (f.object.start_date || Date.today) %>
      <%= f.text_field :start_date, :class => "datepicker", :value => l(start_date) %>
    </div>
    
    <div class="field">
      <%= f.label :end_date %><br />
      <% end_date = (f.object.end_date || Date.today) %>
      <%= f.text_field :end_date, :class => "datepicker", :value => l(end_date) %>
    </div>

    <div class="field">
      <%= f.label :summary %><br />
      <%= f.text_area :summary %>
    </div>
  <% end %>
  
  <%= field_set_tag 'Content' do -%> 
    <div class="field">
      <%= f.label :main_content %><br />
      <%= f.text_area :main_content, :class => 'tinymce' %>
    </div>
  <% end %>
  
  <%= field_set_tag 'Images' do -%> 
    <%= f.image_field :image, :alt => true %>
  <% end %>
  
  <%= field_set_tag 'Categories' do -%> 
  	<p class="admin_note">
  		Type a comma seperated list of categories for this news article here.  Press ',' between each entry.
  		Or select from recently used categories below.
  	</p>
    <div class="field">
  	  <%= f.tag_field :categories %>
    </div> 
  <% end %>
  
  <%= field_set_tag 'Settings' do -%>
    <div class="field">
      <%= f.label :display %><br />
      <%= f.check_box :display %>
    </div>    
  <% end -%>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>					

app/views/admin/events/edit.html.erb
<%- title "Edit #{ Event.model_name.human }" %>

<div class="admin_functions">
  <%= link_to 'Back', admin_events_path %>
</div>

<%= render 'form' %>

app/views/admin/events/index.html.erb
<% title Event.model_name.human.pluralize %>

<div class="admin_functions">
  <%= link_to "New #{ Event.model_name.human }", new_admin_event_path %>
</div>

<%= render 'admin/shared/search' %>

<%= informant_table @events, {
      :headings => [ :headline, :summary, :start_date, :end_date, :display, '', '', '' ], 
      :body => [
        :headline,
        it_shorten(:summary),
        lambda{|x| l x.start_date},
        lambda{|x| l x.end_date if x.end_date?},
        it_ajax_toggle(:display),
        it_edit_images(:image),
        it_edit,
        it_destroy
      ]
    } %>

<%= paginate @events %>

app/views/admin/events/new.html.erb
<% title "New #{ Event.model_name.human }" %>

<div class="admin_functions">
  <%= link_to 'Back', admin_events_path %>
</div>

<%= render 'form' %>