config/routes.rb
HullBid2013::Application.routes.draw do

  namespace :admin do  end

  resources :achievements, :only => [:show]
  resources :articles, :only => [:index, :show]
  resources :standalone_articles, :only => [:index, :show], path: 'covid-19-support'
  resources :businesses, :only => [:index]
  resources :business_highlights, :only => [:show]
  resources :contacts, :only => [:new, :create]
  resources :emails, :only => [:show]
  resources :events, :only => [:index, :show]
  resources :event_galleries, :only => [:index, :show]
  resources :faqs, :only => [:index]
  resources :newsletter_subscribers, :only => [:create]
  resources :pages, :only => [:show]
  resources :resources, :only => [:index]
  resources :team_members, :only => [:index]

  namespace :admin do
    manticore_resources :dine_week_participants
    manticore_resources :faqs
    manticore_resources :footfall_data_entries
    manticore_resources :project_images
    manticore_resources :resources
    manticore_resources :event_galleries do
      chronicler_resources :event_gallery_images
    end
    chronicler_resources :achievements
    chronicler_resources :articles
    chronicler_resources :banners
    chronicler_resources :businesses
    chronicler_resources :business_highlights
    chronicler_resources :default_gallery_images
    chronicler_resources :emails do
      post 'change_template', :on => :member
      post 'new_item', :on => :member
      post 'destroy_item', :on => :member
      post 'create_campaign', :on => :member
      post 'update_campaign', :on => :member
      post 'send_test', :on => :member
      post 'send_now', :on => :member
    end
    chronicler_resources :events
    chronicler_resources :pages
    chronicler_resources :partners
    chronicler_resources :projects
    chronicler_resources :team_members
  end

  match "/accessibility" => "application#accessibility"
  match "/site_map" => "application#site_map"
  match "/rss" => "application#rss"

  root :to => "application#index"

  mount Manticore::Engine => "/admin"

end

app/models/achievement.rb
class Achievement < ActiveRecord::Base
  acts_as_taggable
  
  mount_uploader :image, AchievementImageUploader
  
  validates :name, :summary, :main_content, :date, {:presence => true}
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController

  def show
    @achievements = Achievement.where(["display = ? AND id != ?", true, params[:id].to_i]).order(:date)
    @achievement = Achievement.find(params[:id])
    @business_highlight = BusinessHighlight.where(:display => true).order("date desc").first
  end

end

app/controllers/admin/achievements_controller.rb
module Admin
  class AchievementsController < Manticore::ApplicationController

    helper :form
    crops_images_for Achievement, :image, { :show => { :fit => [440, 1000] } }

    def index
      @achievements = Achievement.where(
        ["name LIKE :search OR summary LIKE :search", {:search => "%#{params[:search]}%"}]
      ).order(params[:order] ||= "date DESC").page(params[:page]).per(10)
    end
    
    def new
      @achievement = Achievement.new
    end
    
    def create
      @achievement = Achievement.new(params[:achievement])
      if @achievement.save
        redirect_to admin_achievements_path, :notice => "Achievement successfully created."
      else
        render :action => 'new'
      end
    end

    def edit
      @achievement = Achievement.find(params[:id])
    end
    
    def update
      @achievement = Achievement.find(params[:id])
      if @achievement.update_attributes(params[:achievement])
        redirect_to admin_achievements_path, :notice => "Achievement successfully updated."
      else
        render :action => 'edit'
      end
    end
    
    def destroy
      @achievement = Achievement.find(params[:id])
      @achievement.destroy
      redirect_to admin_achievements_path, :notice => "Achievement destroyed."
    end
    
  end
end

app/views/admin/achievements/_form.html.erb
<%= form_for([:admin, @achievement]) do |f| %>

  <%= f.error_messages %>

  <%= field_set_tag 'Basic' do -%>
    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>

    <div class="field">
      <%= f.label :date %><br />
      <% date = (f.object.date || Date.today) %>
      <%= f.text_field :date, :class => "datepicker", :value => l(date) %>
    </div>

    <div class="field">
      <%= f.label :summary %><br />
      <%= f.text_area :summary %>
    </div>
  <% end %>
  
  <%= field_set_tag 'Content' do -%>
    <div class="field">
      <%= f.label :main_content %><br />
      <%= f.text_area :main_content, :class => 'tinymce' %>
    </div>    
  <% end -%>

  <%= field_set_tag 'Images' do -%>
    <%= f.image_field :image, :alt => true %>
  <% end -%>
  
  <%# At the minute this module appears on the front in the style of business highlights. 
      Uncomment below if you are changing it to be in the style of news. %>
  <!--
  <%#= field_set_tag 'Categories' do -%> 
  	<p class="admin_note">
  		Type a comma seperated list of categories for this news article here.  Press ',' between each entry.
  		Or select from recently used categories below.
  	</p>
    <div class="field">
  	  <%#= f.tag_field :tag %>
    </div>
  <%# end %>
  -->

  <%= field_set_tag 'Settings' do -%>
    <div class="field">
      <%= f.label :display %><br />
      <%= f.check_box :display %>
    </div>    
  <% end -%>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>					

app/views/admin/achievements/edit.html.erb
<%- title "Edit #{ Achievement.model_name.human }" %>

<div class="admin_functions">
  <%= link_to 'Back', admin_achievements_path %>
</div>

<%= render 'form' %>

app/views/admin/achievements/index.html.erb
<% title Achievement.model_name.human.pluralize %>

<div class="admin_functions">
  <%= link_to "New #{ Achievement.model_name.human }", new_admin_achievement_path %>
</div>

<%= render 'admin/shared/search' %>

<%= informant_table @achievements, {
      :headings => [ :name, :summary, :date, :display, '', '', '' ], 
      :body => [ 
        :name, 
        it_shorten(:summary), 
        lambda{|x| l x.date}, 
        it_ajax_toggle(:display), 
        it_edit_images(:image), 
        it_edit, 
        it_destroy 
      ]
    } %>

<%= paginate @achievements %>

app/views/admin/achievements/new.html.erb
<% title "New #{ Achievement.model_name.human }" %>

<div class="admin_functions">
  <%= link_to 'Back', admin_achievements_path %>
</div>

<%= render 'form' %>